// !!! This is a file automatically generated by hipify!!!
/******************************************************************************
 * Copyright (c) 2024, Tri Dao.
 ******************************************************************************/

#pragma once

#include <tuple>

#if !defined(__CUDACC_RTC__)
#include "hip/hip_runtime.h"
#endif

#define CHECK_CUDA(call)                                                                            \
  do {                                                                                              \
    hipError_t status_ = call;                                                                     \
    if (status_ != hipSuccess) {                                                                   \
      fprintf(stderr, "CUDA error (%s:%d): %s\n", __FILE__, __LINE__, hipGetErrorString(status_)); \
      exit(1);                                                                                      \
    }                                                                                               \
  } while (0)

inline int get_current_device() {
  int device;
  CHECK_CUDA(hipGetDevice(&device));
  return device;
}

inline std::tuple<int, int> get_compute_capability(int device) {
  int capability_major, capability_minor;
  CHECK_CUDA(hipDeviceGetAttribute(&capability_major, hipDeviceAttributeComputeCapabilityMajor, device));
  CHECK_CUDA(hipDeviceGetAttribute(&capability_minor, hipDeviceAttributeComputeCapabilityMinor, device));
  return {capability_major, capability_minor};
}

inline int get_num_sm(int device) {
  int multiprocessor_count;
  CHECK_CUDA(hipDeviceGetAttribute(&multiprocessor_count, hipDeviceAttributeMultiprocessorCount, device));
  return multiprocessor_count;
}
